RESET_STYLE = "\033[0m"

FG_RESET = 1
FG_BLACK = 30
FG_RED = 31
FG_GREEN = 32
FG_YELLOW = 33
FG_BLUE = 34
FG_MAGENTA = 35
FG_CYAN = 36
FG_WHITE = 37
FG_GRAY = 90
FG_BRIGHT_RED = 91
FG_BRIGHT_GREEN = 92
FG_BRIGHT_YELLOW = 93
FG_BRIGHT_BLUE = 94
FG_BRIGHT_MAGENTA = 95
FG_BRIGHT_CYAN = 96
FG_BRIGHT_WHITE = 97

BG_RESET = 31
BG_BLACK = 40
BG_RED = 41
BG_GREEN = 42
BG_YELLOW = 43
BG_BLUE = 44
BG_MAGENTA = 45
BG_CYAN = 46
BG_WHITE = 47
BG_GRAY = 100
BG_BRIGHT_RED = 101
BG_BRIGHT_GREEN = 102
BG_BRIGHT_YELLOW = 103
BG_BRIGHT_BLUE = 104
BG_BRIGHT_MAGENTA = 105
BG_BRIGHT_CYAN = 106
BG_BRIGHT_WHITE = 107

DEFAULT_WARN_COLOR = "yellow"
DEFAULT_FAIL_COLOR = "red"
DEFAULT_SUCCESS_COLOR = "green"
DEFAULT_TIME_COLOR = "blue"

DEFAULT_WARN_SIGN_COLOR = "yellow"
DEFAULT_FAIL_SIGN_COLOR = "red"
DEFAULT_SUCCESS_SIGN_COLOR = "green"
DEFAULT_TIME_SIGN_COLOR = "blue"

DEFAULT_WARN_BRACKET_COLOR = "yellow"
DEFAULT_FAIL_BRACKET_COLOR = "red"
DEFAULT_SUCCESS_BRACKET_COLOR = "green"
DEFAULT_TIME_BRACKET_COLOR = "blue"

DEFAULT_WARN_SIGN = "!"
DEFAULT_FAIL_SIGN = "-"
DEFAULT_SUCCESS_SIGN = "+"
DEFAULT_TIME_SIGN = "TIME"

DEFAULT_WARN_BRACKET_SIGN = None
DEFAULT_FAIL_BRACKET_SIGN = None
DEFAULT_SUCCESS_BRACKET_SIGN = None
DEFAULT_TIME_BRACKET_SIGN = None

DEFAULT_WARN_BACKGROUND_COLOR = None
DEFAULT_FAIL_BACKGROUND_COLOR = None
DEFAULT_SUCCESS_BACKGROUND_COLOR = None
DEFAULT_TIME_BACKGROUND_COLOR = None

DEFAULT_BRACKET_STYLE = "SQUARE"
DEFAULT_IS_UNDERLINED = False